Feat/improve header toolbar
assurance-maladie-digital/design-system-v3 pull request #221
Opened 2024-11-21 16:13 UTC by VachetVirginie

## Description

## Stories

## Type de changement

- Nouvelle fonctionnalité
- Correction de bug
- Changement cassant
- Refactoring
- Maintenance
- Documentation
- Ce changement nécessite une mise à jour de la documentation

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Le composant est conforme aux maquettes (tokens)
- [ ] Le composant est fonctionnel
- [ ] Le composant est responsive (mobile, tablet et desktop)
- [ ] Le composant répond aux critères d'accessibilité (test Tanaguru + A11y linter)
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai mis en place une stories pour ma fonctionnalité / fix /...
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications

2024-11-22 08:11 UTC, DavidFyon commented on src/components/HeaderToolbar/HeaderToolbar.vue
> +  &:hover {
A suuprimer

2024-11-22 08:14 UTC, DavidFyon requested changes

2024-11-22 08:14 UTC, DavidFyon commented on src/components/Customs/CustomInputSelect/CustomInputSelect.vue
> +	onMounted(() => {
A voir si on peux pas gérer ça côté HeaderToolbar ou alors mettre une condition car ça impacte le composant alors que c'est un cas d'usage spécifique à HeaderToolbar :

![Capture d’écran 2024-11-22 à 09 14 00](https://github.com/user-attachments/assets/583408ed-eb14-46cd-bbb3-8724dd2afcb8)

2024-11-22 09:49 UTC, VachetVirginie commented on src/components/HeaderToolbar/HeaderToolbar.vue
> +  &:hover {
Si je le supprime les a droite seront primary comme c'etait à l'origine et dtu m'a demande hier de le mettre iso avec Ameli.fr

2024-11-25 08:14 UTC, DavidFyon approved these changes

2024-11-25 08:16 UTC, merged