cookies selection
assurance-maladie-digital/design-system-v3 pull request #256
Opened 2024-12-09 10:34 UTC by 4dr1en

## Description

Ajout des composants de choix de cookies

## Stories

http://localhost:6006/?path=/docs/templates-cookiesselection--docs
http://localhost:6006/?path=/docs/composants-feedback-cookiebanner--docs

## Type de changement

- Nouvelle fonctionnalité

## Checklist

- [ ] Ma Pull Request pointe vers la bonne branche
- [ ] Le composant est conforme aux maquettes (tokens)
- [ ] Le composant est fonctionnel
- [ ] Le composant est responsive (mobile, tablet et desktop)
- [ ] Le composant répond aux critères d'accessibilité (test Tanaguru + A11y linter)
- [ ] J'ai effectué une review de mon propre code
- [ ] J'ai commenté mon code, en particulier dans les parties difficiles à comprendre
- [ ] J'ai mis en place une stories pour ma fonctionnalité / fix /...
- [ ] Mes modifications ne génèrent aucun nouveau warning
- [ ] J'ai ajouté des tests qui prouvent que mon correctif est efficace ou que ma fonctionnalité fonctionne
- [ ] Les tests unitaires passent localement avec mes modifications

2024-12-09 14:16 UTC, DavidFyon requested changes
- [x] il manque les sourceCode sur les stories pour les cookies
- [ ] sur la version dialogBox il manque la croix pour fermer (on doit pouvoir quitter sans valider)
- [ ] il manque la version qui se déplie dans le composant ?

2024-12-09 14:18 UTC, 4dr1en commented
>     * il manque la version qui se déplie dans le composant ?

De quel version s’agit il ?

2024-12-09 14:36 UTC, VachetVirginie approved these changes

2024-12-17 14:30 UTC, DavidFyon approved these changes

2024-12-17 14:44 UTC, merged