Feat/add nir field
assurance-maladie-digital/design-system-v3 pull request #264
Opened 2024-12-12 08:53 UTC by VachetVirginie

```
<script lang="ts" setup>
	import Nirfield from '@/components/NirField/NirField.vue'
	import { ref } from 'vue'

	const model = ref('')
	const nirFieldRef = ref() // Référence Vue pour accéder au composant enfant

	const handleSubmit = () => {
		// Appeler la méthode exposée `validateOnSubmit` via la référence
		const isValid = nirFieldRef.value?.validateOnSubmit()
		if (!isValid) {
			alert('Corrigez les erreurs avant de soumettre !')
		}
		else {
			alert('Formulaire soumis avec succès !')
		}
	}

	// Exemple de règles personnalisées
	const customNumberRules = [
		{
			type: 'minLength',
			options: {
				length: 10, message: 'Le NIR doit avoir au moins 10 caractères.', successMessage: 'Le NIR a une longueur valide.',
			},
		},
	]
</script>

<template>
	<main>
		<form
			class="mx-16 my-6"
			@submit.prevent="handleSubmit"
		>
			<Nirfield
				ref="nirFieldRef"
				v-model="model"
				:custom-number-rules="customNumberRules"
				:display-key="true"
				outlined
				required
			/>
			<button type="submit">
				Soumettre
			</button>
		</form>
	</main>
</template>

```

2024-12-13 12:52 UTC, DavidFyon requested changes
- Enlever espace en trop doc + enlever story outlined : 
![Capture d’écran 2024-12-13 à 13 48 11](https://github.com/user-attachments/assets/5e090ae9-5b53-4bd5-aa06-73cfc95aa7a9)
![Capture d’écran 2024-12-13 à 14 30 37](https://github.com/user-attachments/assets/7d463ff7-decc-4375-9f09-78645e48e01f)

- Label :
Changer NIR par Numéro de sécurité sociale
![Capture d’écran 2024-12-13 à 14 30 27](https://github.com/user-attachments/assets/f430794b-f493-4622-8fd8-78bb4b59dcff)


- Messages d'erreur :
-Est-ce qu'il ne faudrait pas enlever la clé est invalide (car vide) et juste mettre 
Le champs NIR est requis ?  ou juste la clé du numero... 2 caractères ? (à discuter)
-Si le champ numéro est valide est qu'il ne doit pas passer en checked ?
![Capture d’écran 2024-12-13 à 11 53 21](https://github.com/user-attachments/assets/7ecd0770-a07d-4ae5-8b24-f53b5fb7c467)

- Soucis sur le hint des nombres de caractères (devrait être 12/13)
![Capture d’écran 2024-12-13 à 14 11 37](https://github.com/user-attachments/assets/210fec68-df39-4da1-a242-ab174b91bd53)

- La clé du numéro de sécurité sociale doit contenir 2 chiffres (au lieu de caractères ?).
Est-ce que "le clé NIR est invalide" n'est pas en trop ? ou fusionner les 2 messages ?
![Capture d’écran 2024-12-13 à 14 26 10](https://github.com/user-attachments/assets/a0f65516-8490-4bbc-b892-d08a02a1cc4e)

2024-12-13 14:46 UTC, DavidFyon commented on src/components/NirField/NirField.vue
> +				message: 'Le numero de securite sociale est invalide.',
message: 'Le numero de sécurité sociale est invalide.',

2024-12-13 15:06 UTC, DavidFyon commented on src/components/NirField/NirField.vue
> +		numberLabel: 'Numero de securite sociale',
numberLabel: 'Numero de sécurité sociale',

2024-12-18 14:58 UTC, 4dr1en commented
-  [] Il faudrait une gestion de focus pour passer automatiquement du champ number au champ clé et inversement
-  [] Il ne faudrait pas avoir de message de succès quand seulement la première partie et complété 
![image](https://github.com/user-attachments/assets/34c0d420-cb15-4aee-a125-d08bbe08c4af)
- [] Il ne devrait pas être possible d'afficher a la fois un tooltip a gauche et a droite
![image](https://github.com/user-attachments/assets/d633bcf6-f070-4712-8564-e086876e781b)
-  [] il faudrait mettre des descriptions et les types des props dans la doc

2024-12-18 15:02 UTC, DavidFyon commented
Story customrules :
Soucis sur le nombre de caractères ?

![Capture d’écran 2024-12-18 à 16 01 23](https://github.com/user-attachments/assets/49fffe28-3004-410e-afb1-78a7da434504)

2024-12-20 09:54 UTC, DavidFyon approved these changes

2024-12-20 09:55 UTC, merged